import {Song} from './song';

export var songs: Song[] = [
	{ song_id:	1,		dj_id: 	30,	name: '#Selfie'},
	{ song_id: 	2,		dj_id:	30,	name: 'Roses'},
	{ song_id:	3,		dj_id:	22, name: 'Shades of Grey'},
	{ song_id: 	4, 		dj_id:	12, name: 'Young Again'},
	{ song_id: 	5, 		dj_id:	12, name: 'Birds Fly'},
	{ song_id: 	6, 		dj_id:	11, name: 'Waves'},
	{ song_id: 	7, 		dj_id:	15, name: 'Wasted'},
	{ song_id: 	8, 		dj_id:	15, name: 'Red Light'},
	{ song_id: 	9, 		dj_id:	22, name: 'Pikachu'},
	{ song_id: 	10, 	dj_id:	16, name: 'Titanium'},
	{ song_id: 	11, 	dj_id:	17, name: 'Levels'	},
	{ song_id: 	12, 	dj_id: 	19, name: 'Scary Monsters and Nice Sprites' },
	{ song_id: 	13, 	dj_id:	17, name: 'Hey Brother'},
	{ song_id: 	14, 	dj_id:	12, name: 'Eclipse'	},
	{ song_id: 	15, 	dj_id:	12, name: 'Spaceman'},
	{ song_id: 	16, 	dj_id: 	20, name: 'Delirious' },
	{ song_id: 	17, 	dj_id:	21, name: 'I Need Your Love'},
	{ song_id: 	18, 	dj_id:	21, name: 'Feel So Close'},
	{ song_id: 	19, 	dj_id:	11, name: 'Wakanda'	},
	{ song_id: 	20, 	dj_id:	26, name: 'Tsunami'	},
	{ song_id: 	21, 	dj_id:	26, name: 'Never Leave'},
	{ song_id: 	22, 	dj_id:	28, name: 'Beautiful World'},
	{ song_id: 	23, 	dj_id:	13, name: 'Animals'	},
	{ song_id: 	24, 	dj_id:	27, name: 'Sun Is Shinning'},
	{ song_id: 	25, 	dj_id:	27, name: 'This Time'},
	{ song_id: 	26, 	dj_id:	24, name: 'Rave after Rave'},
	{ song_id: 	27, 	dj_id:	28, name: 'Gravity'	},
	{ song_id: 	28, 	dj_id:	14, name: 'This Is What It Feel Like'},
	{ song_id: 	29, 	dj_id:	18, name: 'No Beef'},
	{ song_id: 	30, 	dj_id:	29, name: 'Powerful'},
	{ song_id: 	31, 	dj_id:	22, name: 'Las All Night'},
	{ song_id: 	32, 	dj_id:	29, name: 'Bubble Butt'},
	{ song_id: 	33, 	dj_id:	24, name: 'Bigfoot'},
	{ song_id: 	34, 	dj_id:	13, name: 'Forbidden Voices'},
	{ song_id: 	35, 	dj_id:	17, name: 'Addicted To You'},
	{ song_id: 	36, 	dj_id:	16, name: 'Hey Mama'},
	{ song_id: 	37, 	dj_id:	29, name: 'All My Love'},
	{ song_id: 	38, 	dj_id:	11, name: 'The Hum'	},
	{ song_id: 	39, 	dj_id:	17, name: 'Wake Me Up'},
	{ song_id: 	40, 	dj_id:	14, name: 'Ping Pong'},
	{ song_id: 	41, 	dj_id: 	25, name: 'Till the Sky Falls Down' },
	{ song_id: 	42, 	dj_id:	27, name: 'Something New'},
	{ song_id: 	43, 	dj_id:	17, name: 'Lay Me Down'},
	{ song_id: 	44, 	dj_id:	28, name: 'Mystica'	},
	{ song_id: 	45, 	dj_id:	30, name: 'Kenya'	},
	{ song_id: 	46, 	dj_id:	16, name: 'Without You'},
	{ song_id: 	47, 	dj_id:	12, name: 'Cobra'},
	{ song_id: 	48, 	dj_id:	18, name: 'Ten Feet Tall'},
	{ song_id: 	49, 	dj_id:	16, name: 'Sexy Bitch'			},
	{ song_id: 	50, 	dj_id:	15, name: 'I Will Be Here'},
	{ song_id: 	51, 	dj_id:	23, name: 'Years'},
	{ song_id: 	52, 	dj_id:	18, name: 'Take Over Control'},
	{ song_id: 	53, 	dj_id:	30, name: 'Waterbed'},
	{ song_id: 	54, 	dj_id:	11, name: 'Under the Water'},
	{ song_id: 	55, 	dj_id:	11, name: 'Louder'},
	{ song_id: 	56, 	dj_id:	23, name: 'Cool'},
	{ song_id: 	57, 	dj_id:	18, name: 'The Spark'},
	{ song_id: 	58, 	dj_id:	30, name: 'New York City'},
	{ song_id: 	59, 	dj_id:	23, name: 'Heroes'	},
	{ song_id: 	60, 	dj_id:	13, name: 'Wizard'	},
	{ song_id: 	61, 	dj_id:	13, name: 'Turn Up the Speaker'}
];